"""
PoE loot filter generator — build-aware, customizable.

Generates a complete .filter file from a Build and FilterConfig.
Sections are ordered by priority (first match wins in PoE filters).
"""

from __future__ import annotations

import datetime

from pop.build_parser.models import Build
from pop.filter.build_analysis import BuildFilterData, analyze_build_for_filter
from pop.filter.models import FilterConfig, FilterTheme, Strictness, SoundConfig


def generate_filter(build: Build, config: FilterConfig | None = None) -> str:
    """Generate a complete .filter file string from a Build.

    Args:
        build: Parsed PoB Build object.
        config: Optional filter configuration. Uses defaults if None.

    Returns:
        Full text content of a PoE .filter file.
    """
    cfg = config or FilterConfig()
    theme = cfg.theme
    sounds = cfg.sounds
    data = analyze_build_for_filter(build)

    lines: list[str] = []

    # Header
    _section_header(lines, cfg, data)

    # Priority order (first match wins):
    _section_currency_high(lines, theme, sounds)
    _section_currency_mid(lines, theme, sounds, cfg.strictness)
    _section_currency_low(lines, theme, cfg.strictness)
    _section_maps(lines, theme, sounds, cfg.strictness)
    _section_build_gems(lines, theme, sounds, data, cfg)
    _section_build_weapon_bases(lines, theme, sounds, data, cfg.strictness)
    _section_build_armour_bases(lines, theme, data, cfg.strictness)
    if cfg.show_resist_fillers and data.resist_gaps:
        _section_resist_fillers(lines, theme, data)
    if cfg.show_cluster_jewels:
        _section_cluster_jewels(lines, theme, data, cfg.strictness)
    _section_unique_items(lines, theme, sounds, cfg.strictness)
    _section_six_links(lines, theme)
    _section_flasks(lines, theme, cfg.strictness)
    _section_rares(lines, theme, cfg.strictness)
    _section_hide(lines, cfg.strictness)

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------


def _section_header(lines: list[str], cfg: FilterConfig, data: BuildFilterData) -> None:
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    lines.append(f"# =====================================================")
    lines.append(f"# {cfg.filter_name} — Build-Aware Loot Filter")
    lines.append(f"# Generated by Path of Purpose on {now}")
    lines.append(f"# Strictness: {cfg.strictness.value}")
    if data.ascendancy:
        lines.append(f"# Build: Level {data.level} {data.ascendancy}")
    if data.active_gem_names:
        lines.append(f"# Main skills: {', '.join(data.active_gem_names[:5])}")
    if data.weapon_classes:
        lines.append(f"# Weapon: {', '.join(data.weapon_classes)}")
    if data.damage_types:
        lines.append(f"# Damage: {', '.join(data.damage_types)}")
    if data.resist_gaps:
        gaps = [f"{k} {v:+.0f}%" for k, v in data.resist_gaps.items()]
        lines.append(f"# Resist gaps: {', '.join(gaps)}")
    lines.append(f"# =====================================================")
    lines.append("")


def _section_currency_high(
    lines: list[str], theme: FilterTheme, sounds: SoundConfig,
) -> None:
    lines.append("# === HIGH-VALUE CURRENCY ===")
    _block(lines, "Show", [
        'Class == "Currency"',
        'BaseType == "Mirror of Kalandra" "Divine Orb" "Exalted Orb" "Awakener\'s Orb" "Maven\'s Orb" "Fracturing Orb" "Annulment Orb"',
    ], theme.currency_high_text, theme.currency_high_bg, theme.currency_high_border,
        theme.font_size_high, sounds.currency_high, beam="Red", icon="0 Red Star")
    lines.append("")


def _section_currency_mid(
    lines: list[str], theme: FilterTheme, sounds: SoundConfig,
    strictness: Strictness,
) -> None:
    lines.append("# === MID-VALUE CURRENCY ===")
    _block(lines, "Show", [
        'Class == "Currency"',
        'BaseType == "Chaos Orb" "Vaal Orb" "Orb of Regret" "Regal Orb" "Gemcutter\'s Prism" '
        '"Blessed Orb" "Orb of Scouring" "Orb of Fusing" "Cartographer\'s Chisel" '
        '"Orb of Alchemy" "Orb of Unmaking" "Veiled Chaos Orb"',
    ], theme.currency_mid_text, theme.currency_mid_bg, theme.currency_mid_border,
        theme.font_size_medium, sounds.currency_mid, beam="Yellow", icon="1 Yellow Circle")
    lines.append("")


def _section_currency_low(
    lines: list[str], theme: FilterTheme, strictness: Strictness,
) -> None:
    lines.append("# === LOW-VALUE CURRENCY ===")
    if strictness in (Strictness.ENDGAME, Strictness.ULTRA_STRICT):
        # Hide scrolls and low orbs at endgame
        _block(lines, "Hide", [
            'Class == "Currency"',
            'BaseType == "Scroll of Wisdom" "Portal Scroll" "Orb of Transmutation" '
            '"Orb of Augmentation" "Armourer\'s Scrap" "Blacksmith\'s Whetstone"',
        ], theme.currency_low_text, font_size=theme.font_size_tiny)
    else:
        _block(lines, "Show", [
            'Class == "Currency"',
        ], theme.currency_low_text, font_size=theme.font_size_low)
    lines.append("")


def _section_maps(
    lines: list[str], theme: FilterTheme, sounds: SoundConfig,
    strictness: Strictness,
) -> None:
    lines.append("# === MAPS ===")
    # High tier maps
    _block(lines, "Show", [
        'Class == "Maps"',
        'MapTier >= 14',
    ], theme.map_text, border=theme.map_border,
        font_size=theme.font_size_high, sound=sounds.map_drop,
        beam="White", icon="0 White Square")

    # Mid tier
    _block(lines, "Show", [
        'Class == "Maps"',
        'MapTier >= 11',
    ], theme.map_text, border=theme.map_border, font_size=theme.font_size_medium)

    if strictness == Strictness.ULTRA_STRICT:
        _block(lines, "Hide", [
            'Class == "Maps"',
            'MapTier < 11',
        ], theme.map_text, font_size=theme.font_size_tiny)
    else:
        _block(lines, "Show", [
            'Class == "Maps"',
        ], theme.map_text, font_size=theme.font_size_low)
    lines.append("")


def _section_build_gems(
    lines: list[str], theme: FilterTheme, sounds: SoundConfig,
    data: BuildFilterData, cfg: FilterConfig,
) -> None:
    all_gems = list(set(data.active_gem_names + data.support_gem_names))
    if not all_gems:
        return

    lines.append("# === BUILD GEMS ===")
    gem_list = " ".join(f'"{g}"' for g in all_gems)
    _block(lines, "Show", [
        'Class == "Gems"',
        f'BaseType == {gem_list}',
    ], theme.gem_text, border=theme.gem_border,
        font_size=theme.font_size_medium,
        sound=sounds.gem_drop if sounds.gem_drop else 0,
        beam="Cyan Temp")

    # Other gems
    if cfg.strictness in (Strictness.ENDGAME, Strictness.ULTRA_STRICT):
        _block(lines, "Show", [
            'Class == "Gems"',
            'GemLevel >= 19',
        ], theme.gem_text, font_size=theme.font_size_low)
        if not cfg.show_leveling_gems:
            _block(lines, "Hide", ['Class == "Gems"'])
    else:
        _block(lines, "Show", ['Class == "Gems"'], theme.gem_text,
               font_size=theme.font_size_low)
    lines.append("")


def _section_build_weapon_bases(
    lines: list[str], theme: FilterTheme, sounds: SoundConfig,
    data: BuildFilterData, strictness: Strictness,
) -> None:
    if not data.weapon_classes:
        return

    lines.append("# === BUILD WEAPON BASES ===")
    class_list = " ".join(f'"{c}"' for c in data.weapon_classes)

    # High ilvl weapon bases
    _block(lines, "Show", [
        f'Class == {class_list}',
        'Rarity <= Rare',
        'ItemLevel >= 82',
    ], theme.build_gear_text, theme.build_gear_bg, theme.build_gear_border,
        theme.font_size_medium, sounds.build_gear, beam="Green Temp")

    if strictness != Strictness.ULTRA_STRICT:
        _block(lines, "Show", [
            f'Class == {class_list}',
            'Rarity <= Rare',
            'ItemLevel >= 60',
        ], theme.build_gear_text, border=theme.build_gear_border,
            font_size=theme.font_size_low)
    lines.append("")


def _section_build_armour_bases(
    lines: list[str], theme: FilterTheme, data: BuildFilterData,
    strictness: Strictness,
) -> None:
    if not data.armour_type or strictness == Strictness.LEVELING:
        return

    lines.append("# === BUILD ARMOUR BASES ===")
    # Map armour type to PoE filter classes
    armour_classes = {
        "es": ["Body Armours", "Helmets", "Boots", "Gloves", "Shields"],
        "evasion": ["Body Armours", "Helmets", "Boots", "Gloves", "Shields"],
        "armour": ["Body Armours", "Helmets", "Boots", "Gloves", "Shields"],
        "hybrid": ["Body Armours", "Helmets", "Boots", "Gloves", "Shields"],
    }
    classes = armour_classes.get(data.armour_type, [])
    if not classes:
        return

    class_list = " ".join(f'"{c}"' for c in classes)
    _block(lines, "Show", [
        f'Class == {class_list}',
        'Rarity <= Rare',
        'ItemLevel >= 84',
        'LinkedSockets >= 5',
    ], theme.build_gear_text, border=theme.build_gear_border,
        font_size=theme.font_size_medium, beam="Green Temp")
    lines.append("")


def _section_resist_fillers(
    lines: list[str], theme: FilterTheme, data: BuildFilterData,
) -> None:
    lines.append("# === RESIST FILLER GEAR ===")
    lines.append("# Your build needs these resists:")

    resist_mods = []
    if "fire" in data.resist_gaps:
        resist_mods.append('"to Fire Resistance"')
    if "cold" in data.resist_gaps:
        resist_mods.append('"to Cold Resistance"')
    if "lightning" in data.resist_gaps:
        resist_mods.append('"to Lightning Resistance"')
    if "chaos" in data.resist_gaps:
        resist_mods.append('"to Chaos Resistance"')

    if not resist_mods:
        return

    mod_list = " ".join(resist_mods)
    _block(lines, "Show", [
        'Class == "Rings" "Amulets" "Belts"',
        'Rarity == Rare',
        'Identified True',
        f'HasExplicitMod {mod_list}',
    ], theme.resist_filler_text, border=theme.resist_filler_border,
        font_size=theme.font_size_medium)
    lines.append("")


def _section_cluster_jewels(
    lines: list[str], theme: FilterTheme, data: BuildFilterData,
    strictness: Strictness,
) -> None:
    lines.append("# === CLUSTER JEWELS ===")

    # Map damage types to cluster jewel enchant keywords
    cluster_keywords = {
        "fire": ["Fire Damage", "Burning Damage"],
        "cold": ["Cold Damage", "Freeze"],
        "lightning": ["Lightning Damage", "Shock"],
        "chaos": ["Chaos Damage", "Poison"],
        "physical": ["Physical Damage", "Attack Damage"],
    }

    enchant_terms = []
    for dtype in data.damage_types:
        for kw in cluster_keywords.get(dtype, []):
            enchant_terms.append(f'"{kw}"')

    if enchant_terms:
        terms = " ".join(enchant_terms)
        _block(lines, "Show", [
            'BaseType == "Large Cluster Jewel" "Medium Cluster Jewel" "Small Cluster Jewel"',
            f'EnchantmentPassiveNode {terms}',
        ], theme.build_gear_text, border=theme.build_gear_border,
            font_size=theme.font_size_medium)
    else:
        # Show all cluster jewels if no specific type detected
        _block(lines, "Show", [
            'BaseType == "Large Cluster Jewel" "Medium Cluster Jewel" "Small Cluster Jewel"',
        ], theme.build_gear_text, font_size=theme.font_size_low)
    lines.append("")


def _section_unique_items(
    lines: list[str], theme: FilterTheme, sounds: SoundConfig,
    strictness: Strictness,
) -> None:
    lines.append("# === UNIQUE ITEMS ===")
    _block(lines, "Show", [
        'Rarity == Unique',
    ], theme.unique_text, border=theme.unique_border,
        font_size=theme.font_size_medium, sound=sounds.unique_drop,
        beam="Orange Temp", icon="1 Orange Diamond")
    lines.append("")


def _section_six_links(lines: list[str], theme: FilterTheme) -> None:
    lines.append("# === 6-LINKS ===")
    _block(lines, "Show", [
        'LinkedSockets >= 6',
    ], "255 0 0", "255 255 255 255", "255 0 0",
        theme.font_size_high, sound=1, beam="Red", icon="0 Red Star")
    lines.append("")


def _section_flasks(
    lines: list[str], theme: FilterTheme, strictness: Strictness,
) -> None:
    lines.append("# === FLASKS ===")
    if strictness == Strictness.ULTRA_STRICT:
        _block(lines, "Show", [
            'Class == "Utility Flasks"',
            'Quality >= 15',
        ], font_size=theme.font_size_low)
        _block(lines, "Hide", ['Class == "Flasks"'])
    elif strictness == Strictness.ENDGAME:
        _block(lines, "Show", [
            'Class == "Utility Flasks"',
        ], font_size=theme.font_size_low)
        _block(lines, "Hide", [
            'Class == "Life Flasks" "Mana Flasks"',
            'ItemLevel >= 70',
        ])
    else:
        _block(lines, "Show", ['Class == "Flasks"'],
               font_size=theme.font_size_low)
    lines.append("")


def _section_rares(
    lines: list[str], theme: FilterTheme, strictness: Strictness,
) -> None:
    lines.append("# === RARE ITEMS ===")
    if strictness == Strictness.ULTRA_STRICT:
        # Only show jewellery rares
        _block(lines, "Show", [
            'Class == "Rings" "Amulets" "Belts"',
            'Rarity == Rare',
            'ItemLevel >= 75',
        ], font_size=theme.font_size_low)
        _block(lines, "Show", [
            'Rarity == Rare',
            'ItemLevel >= 75',
            'LinkedSockets >= 5',
        ], font_size=theme.font_size_low)
    elif strictness == Strictness.ENDGAME:
        _block(lines, "Show", [
            'Rarity == Rare',
            'ItemLevel >= 75',
        ], font_size=theme.font_size_low)
    else:
        _block(lines, "Show", ['Rarity == Rare'],
               font_size=theme.font_size_low)
    lines.append("")


def _section_hide(lines: list[str], strictness: Strictness) -> None:
    lines.append("# === HIDE EVERYTHING ELSE ===")
    if strictness == Strictness.LEVELING:
        # Show normals/magics during leveling (smaller text)
        _block(lines, "Show", ['Rarity <= Magic'], font_size=20)
    elif strictness == Strictness.MAPPING:
        _block(lines, "Hide", [
            'Rarity == Normal',
            'ItemLevel >= 65',
        ])
        _block(lines, "Show", [], font_size=20)
    else:
        _block(lines, "Hide", ['Rarity <= Magic'])


# ---------------------------------------------------------------------------
# Block builder
# ---------------------------------------------------------------------------


def _block(
    lines: list[str],
    block_type: str,  # "Show" or "Hide"
    conditions: list[str],
    text_color: str | None = None,
    bg_color: str | None = None,
    border: str | None = None,
    font_size: int | None = None,
    sound: int = 0,
    beam: str | None = None,
    icon: str | None = None,
) -> None:
    """Append a filter block to lines."""
    lines.append(block_type)
    for cond in conditions:
        lines.append(f"    {cond}")
    if text_color:
        lines.append(f"    SetTextColor {text_color}")
    if bg_color:
        lines.append(f"    SetBackgroundColor {bg_color}")
    if border:
        lines.append(f"    SetBorderColor {border}")
    if font_size:
        lines.append(f"    SetFontSize {font_size}")
    if sound > 0:
        lines.append(f"    PlayAlertSound {sound} 300")
    if beam:
        lines.append(f"    PlayEffect {beam}")
    if icon:
        lines.append(f"    MinimapIcon {icon}")
    lines.append("")
